/*
 * This source file was generated by the Gradle 'init' task
 */
package knowledgeassistant;

public class App {
    public String getGreeting() {        
        return null;
        //return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
